In [55]:
import nltk
import warnings
import string
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
warnings.filterwarnings('ignore')
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split


In [56]:
df = pd.read_csv(r"C:\Users\Parth Tripathi\Downloads\Twitter_Data (2).csv")
df.head()

clean_text  category
0  when modi promised “minimum government maximum...      -1.0
1  talk all the nonsense and continue all the dra...       0.0
2  what did just say vote for modi  welcome bjp t...       1.0
3  asking his supporters prefix chowkidar their n...       1.0
4  answer who among these the most powerful world...       1.0

In [57]:
df.shape

(162980, 2)

In [58]:
df = df.iloc[:10000,:]

In [59]:
df.dropna(inplace = True)

In [60]:
df['category'].replace([-1.0,0.0,1.0],['negative','netural','postive'] ,inplace = True)

In [61]:
x = df['clean_text'].to_numpy()
y = df['category'].to_numpy()

In [62]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [63]:
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.2, random_state=42)

In [64]:
tfidf = TfidfVectorizer()
x_train_vect = tfidf.fit_transform(x_train)
x_val_vect = tfidf.transform(x_val)
x_test_vect = tfidf.transform(x_test)

In [65]:
print(x_train_vect.shape)

(5599, 14058)


In [66]:
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train_vect,y_train)

KNeighborsClassifier()

In [67]:
knn_pred=knn.predict(x_test_vect)
print(confusion_matrix(y_test,knn_pred))
print(classification_report(y_test,knn_pred))
accuracy=accuracy_score(y_test,knn_pred)

[[250 367 116]
 [ 93 752 169]
 [166 594 493]]
              precision    recall  f1-score   support

    negative       0.49      0.34      0.40       733
     netural       0.44      0.74      0.55      1014
     postive       0.63      0.39      0.49      1253

    accuracy                           0.50      3000
   macro avg       0.52      0.49      0.48      3000
weighted avg       0.53      0.50      0.49      3000



In [68]:
import pickle
with open('knn_model.pkl', 'wb') as file:
    pickle.dump(knn, file)